blank_issues_enabled: false
contact_links:
  - name: Preguntas o Soporte
    url: https://github.com/wDona/Burnt-out-Proyecto-Final/discussions
    about: Si no es un error o una mejora, por favor usa las discusiones.