blank_issues_enabled: false
contact_links:
  - name: Preguntame lo que quieras
    url: https://github.com/wDona/Burnt-out/discussions
    about: Si no es un error o una mejora, por favor usa las discusiones.
